-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ObjectTrackerHDL\ComplexDivide.vhd
-- Created: 2024-12-03 00:37:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: ComplexDivide
-- Source Path: ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide
-- Hierarchy Level: 5
-- Model version: 3.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY ComplexDivide IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Dividend_re                       :   IN    std_logic_vector(27 DOWNTO 0);  -- sfix28_En8
        Dividend_im                       :   IN    std_logic_vector(27 DOWNTO 0);  -- sfix28_En8
        Divisor                           :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En8
        Quotient_re                       :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En12
        Quotient_im                       :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En12
        );
END ComplexDivide;


ARCHITECTURE rtl OF ComplexDivide IS

  -- Component Declarations
  COMPONENT Divide3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dividend_in                     :   IN    std_logic_vector(43 DOWNTO 0);  -- sfix44_En16
          divisor_in                      :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En8
          quotient                        :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En12
          );
  END COMPONENT;

  COMPONENT Divide4
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dividend_in                     :   IN    std_logic_vector(43 DOWNTO 0);  -- sfix44_En16
          divisor_in                      :   IN    std_logic_vector(35 DOWNTO 0);  -- sfix36_En8
          quotient                        :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En12
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Divide3
    USE ENTITY work.Divide3(rtl);

  FOR ALL : Divide4
    USE ENTITY work.Divide4(rtl);

  -- Signals
  SIGNAL Dividend_re_signed               : signed(27 DOWNTO 0);  -- sfix28_En8
  SIGNAL Dividend_im_signed               : signed(27 DOWNTO 0);  -- sfix28_En8
  SIGNAL Data_Type_Conversion_out1        : signed(43 DOWNTO 0);  -- sfix44_En16
  SIGNAL Delay14_out1                     : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL Data_Type_Conversion1_out1       : signed(43 DOWNTO 0);  -- sfix44_En16
  SIGNAL Delay15_out1                     : std_logic_vector(23 DOWNTO 0);  -- ufix24

BEGIN
  u_Divide3 : Divide3
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dividend_in => std_logic_vector(Data_Type_Conversion_out1),  -- sfix44_En16
              divisor_in => Divisor,  -- sfix36_En8
              quotient => Delay14_out1  -- sfix24_En12
              );

  u_Divide4 : Divide4
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dividend_in => std_logic_vector(Data_Type_Conversion1_out1),  -- sfix44_En16
              divisor_in => Divisor,  -- sfix36_En8
              quotient => Delay15_out1  -- sfix24_En12
              );

  Dividend_re_signed <= signed(Dividend_re);

  Data_Type_Conversion_out1 <= resize(Dividend_re_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 44);

  Dividend_im_signed <= signed(Dividend_im);

  Data_Type_Conversion1_out1 <= resize(Dividend_im_signed & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 44);

  Quotient_re <= Delay14_out1;

  Quotient_im <= Delay15_out1;

END rtl;

