open_system('ObjectTrackerHDL');
open_system('gm_ObjectTrackerHDL');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Overlay/VideoOverlay/Divide', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/CurrPreprocess/Divide1', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/CoefficientsUpdate/CoefficientsUpdate/ComplexDivide/Divide4', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide2', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 2 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 'user1');
annotate_port('ObjectTrackerHDL/ObjectTrackerHDL/Track/MaxCorrelation/Divide3', 0, 1, 'Blocks delay absorption: 1 cycles');
