-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ObjectTrackerHDL\Lookup_Table_block4.vhd
-- Created: 2024-12-03 00:37:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Lookup_Table_block4
-- Source Path: ObjectTrackerHDL/ObjectTrackerHDL/Preprocess/PrevPreprocess/Image Statistics/calcMean/Normalization_Var/Lookup 
-- Tabl
-- Hierarchy Level: 6
-- Model version: 3.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ObjectTrackerHDL_pkg.ALL;

ENTITY Lookup_Table_block4 IS
  PORT( in1                               :   IN    std_logic_vector(5 DOWNTO 0);  -- ufix6
        out_rsvd                          :   OUT   std_logic_vector(17 DOWNTO 0)  -- ufix18_En17
        );
END Lookup_Table_block4;


ARCHITECTURE rtl OF Lookup_Table_block4 IS

  -- Constants
  CONSTANT Lookup_Table_data              : vector_of_unsigned18(0 TO 63) := 
    (to_unsigned(16#20000#, 18), to_unsigned(16#10000#, 18), to_unsigned(16#0AAAB#, 18),
     to_unsigned(16#08000#, 18), to_unsigned(16#06666#, 18), to_unsigned(16#05555#, 18),
     to_unsigned(16#04925#, 18), to_unsigned(16#04000#, 18), to_unsigned(16#038E4#, 18),
     to_unsigned(16#03333#, 18), to_unsigned(16#02E8C#, 18), to_unsigned(16#02AAB#, 18),
     to_unsigned(16#02762#, 18), to_unsigned(16#02492#, 18), to_unsigned(16#02222#, 18),
     to_unsigned(16#02000#, 18), to_unsigned(16#01E1E#, 18), to_unsigned(16#01C72#, 18),
     to_unsigned(16#01AF3#, 18), to_unsigned(16#0199A#, 18), to_unsigned(16#01862#, 18),
     to_unsigned(16#01746#, 18), to_unsigned(16#01643#, 18), to_unsigned(16#01555#, 18),
     to_unsigned(16#0147B#, 18), to_unsigned(16#013B1#, 18), to_unsigned(16#012F7#, 18),
     to_unsigned(16#01249#, 18), to_unsigned(16#011A8#, 18), to_unsigned(16#01111#, 18),
     to_unsigned(16#01084#, 18), to_unsigned(16#01000#, 18), to_unsigned(16#00F84#, 18),
     to_unsigned(16#00F0F#, 18), to_unsigned(16#00EA1#, 18), to_unsigned(16#00E39#, 18),
     to_unsigned(16#00DD6#, 18), to_unsigned(16#00D79#, 18), to_unsigned(16#00D21#, 18),
     to_unsigned(16#00CCD#, 18), to_unsigned(16#00C7D#, 18), to_unsigned(16#00C31#, 18),
     to_unsigned(16#00BE8#, 18), to_unsigned(16#00BA3#, 18), to_unsigned(16#00B61#, 18),
     to_unsigned(16#00B21#, 18), to_unsigned(16#00AE5#, 18), to_unsigned(16#00AAB#, 18),
     to_unsigned(16#00A73#, 18), to_unsigned(16#00A3D#, 18), to_unsigned(16#00A0A#, 18),
     to_unsigned(16#009D9#, 18), to_unsigned(16#009A9#, 18), to_unsigned(16#0097B#, 18),
     to_unsigned(16#0094F#, 18), to_unsigned(16#00925#, 18), to_unsigned(16#008FC#, 18),
     to_unsigned(16#008D4#, 18), to_unsigned(16#008AE#, 18), to_unsigned(16#00889#, 18),
     to_unsigned(16#00865#, 18), to_unsigned(16#00842#, 18), to_unsigned(16#00821#, 18),
     to_unsigned(16#00800#, 18));  -- ufix18 [64]

  -- Signals
  SIGNAL in1_unsigned                     : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL prelookup_idx_sat                : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL out_tmp                          : unsigned(17 DOWNTO 0);  -- ufix18_En17

BEGIN
  in1_unsigned <= unsigned(in1);

  
  prelookup_idx_sat <= to_unsigned(16#00#, 6) WHEN in1_unsigned = to_unsigned(16#00#, 6) ELSE
      to_unsigned(16#3F#, 6) WHEN in1_unsigned = to_unsigned(16#3F#, 6) ELSE
      in1_unsigned;

  out_tmp <= Lookup_Table_data(to_integer(prelookup_idx_sat));

  out_rsvd <= std_logic_vector(out_tmp);

END rtl;

