vlib work
vcom  ObjectTrackerHDL_pkg.vhd
vcom  MATLAB_Function.vhd
vcom  Divide.vhd
vcom  VideoOverlay.vhd
vcom  Overlay.vhd
vcom  BankBit.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  LowerRAM.vhd
vcom  SwapAddr.vhd
vcom  UpperRAM.vhd
vcom  CounterDelay.vhd
vcom  CornerTurnMemory.vhd
vcom  Pixel_Control_Bus_Creator.vhd
vcom  pixelBusGenerator.vhd
vcom  SimpleDualPortRAM_generic_block.vhd
vcom  SDFCommutator1.vhd
vcom  RADIX22FFT_SDF1_1.vhd
vcom  RADIX22FFT_CTRL1_1.vhd
vcom  SDFCommutator2.vhd
vcom  RADIX22FFT_SDF2_2.vhd
vcom  RADIX22FFT_CTRL1_2.vhd
vcom  TWDLROM_3_1.vhd
vcom  Complex4Multiply.vhd
vcom  SDFCommutator3.vhd
vcom  RADIX22FFT_SDF1_3.vhd
vcom  RADIX22FFT_CTRL1_3.vhd
vcom  SDFCommutator4.vhd
vcom  RADIX22FFT_SDF2_4.vhd
vcom  RADIX22FFT_CTRL1_4.vhd
vcom  TWDLROM_5_1.vhd
vcom  Complex4Multiply_block.vhd
vcom  SDFCommutator5.vhd
vcom  RADIX22FFT_SDF1_5.vhd
vcom  RADIX22FFT_CTRL1_5.vhd
vcom  SDFCommutator6.vhd
vcom  RADIX22FFT_SDF2_6.vhd
vcom  RADIX22FFT_CTRL1_6.vhd
vcom  TWDLROM_7_1.vhd
vcom  Complex4Multiply_block1.vhd
vcom  SDFCommutator7.vhd
vcom  RADIX22FFT_SDF1_7.vhd
vcom  RADIX22FFT_CTRL1_1_block.vhd
vcom  RADIX2FFT_bitNatural.vhd
vcom  ColumnIFFT.vhd
vcom  SDFCommutator1_block.vhd
vcom  RADIX22FFT_SDF1_1_block.vhd
vcom  RADIX22FFT_CTRL1_1_block1.vhd
vcom  SDFCommutator2_block.vhd
vcom  RADIX22FFT_SDF2_2_block.vhd
vcom  RADIX22FFT_CTRL1_2_block.vhd
vcom  TWDLROM_3_1_block.vhd
vcom  Complex4Multiply_block2.vhd
vcom  SDFCommutator3_block.vhd
vcom  RADIX22FFT_SDF1_3_block.vhd
vcom  RADIX22FFT_CTRL1_3_block.vhd
vcom  SDFCommutator4_block.vhd
vcom  RADIX22FFT_SDF2_4_block.vhd
vcom  RADIX22FFT_CTRL1_4_block.vhd
vcom  TWDLROM_5_1_block.vhd
vcom  Complex4Multiply_block3.vhd
vcom  SDFCommutator5_block.vhd
vcom  RADIX22FFT_SDF1_5_block.vhd
vcom  RADIX22FFT_CTRL1_5_block.vhd
vcom  SDFCommutator6_block.vhd
vcom  RADIX22FFT_SDF2_6_block.vhd
vcom  RADIX22FFT_CTRL1_6_block.vhd
vcom  TWDLROM_7_1_block.vhd
vcom  Complex4Multiply_block4.vhd
vcom  SDFCommutator7_block.vhd
vcom  RADIX22FFT_SDF1_7_block.vhd
vcom  RADIX22FFT_CTRL1_1_block2.vhd
vcom  RADIX2FFT_bitNatural_block.vhd
vcom  RowIFFT.vhd
vcom  alpha2_DIFFT.vhd
vcom  Divide3.vhd
vcom  Divide4.vhd
vcom  ComplexDivide.vhd
vcom  CoefficientsUpdate.vhd
vcom  CoefficientsUpdate_block.vhd
vcom  BankBit_block.vhd
vcom  LowerRAM_block.vhd
vcom  SwapAddr_block.vhd
vcom  UpperRAM_block.vhd
vcom  CounterDelay_block.vhd
vcom  CornerTurnMemory_block.vhd
vcom  Pixel_Control_Bus_Creator_block.vhd
vcom  pixelBusGenerator_block.vhd
vcom  SDFCommutator1_block1.vhd
vcom  RADIX22FFT_SDF1_1_block1.vhd
vcom  RADIX22FFT_CTRL1_1_block3.vhd
vcom  SDFCommutator2_block1.vhd
vcom  RADIX22FFT_SDF2_2_block1.vhd
vcom  RADIX22FFT_CTRL1_2_block1.vhd
vcom  TWDLROM_3_1_block1.vhd
vcom  Complex4Multiply_block5.vhd
vcom  SDFCommutator3_block1.vhd
vcom  RADIX22FFT_SDF1_3_block1.vhd
vcom  RADIX22FFT_CTRL1_3_block1.vhd
vcom  SDFCommutator4_block1.vhd
vcom  RADIX22FFT_SDF2_4_block1.vhd
vcom  RADIX22FFT_CTRL1_4_block1.vhd
vcom  TWDLROM_5_1_block1.vhd
vcom  Complex4Multiply_block6.vhd
vcom  SDFCommutator5_block1.vhd
vcom  RADIX22FFT_SDF1_5_block1.vhd
vcom  RADIX22FFT_CTRL1_5_block1.vhd
vcom  SDFCommutator6_block1.vhd
vcom  RADIX22FFT_SDF2_6_block1.vhd
vcom  RADIX22FFT_CTRL1_6_block1.vhd
vcom  TWDLROM_7_1_block1.vhd
vcom  Complex4Multiply_block7.vhd
vcom  SDFCommutator7_block1.vhd
vcom  RADIX22FFT_SDF1_7_block1.vhd
vcom  RADIX22FFT_CTRL1_1_block4.vhd
vcom  RADIX2FFT_bitNatural_block1.vhd
vcom  ColumnFFT.vhd
vcom  SDFCommutator1_block2.vhd
vcom  RADIX22FFT_SDF1_1_block2.vhd
vcom  RADIX22FFT_CTRL1_1_block5.vhd
vcom  SDFCommutator2_block2.vhd
vcom  RADIX22FFT_SDF2_2_block2.vhd
vcom  RADIX22FFT_CTRL1_2_block2.vhd
vcom  TWDLROM_3_1_block2.vhd
vcom  Complex4Multiply_block8.vhd
vcom  SDFCommutator3_block2.vhd
vcom  RADIX22FFT_SDF1_3_block2.vhd
vcom  RADIX22FFT_CTRL1_3_block2.vhd
vcom  SDFCommutator4_block2.vhd
vcom  RADIX22FFT_SDF2_4_block2.vhd
vcom  RADIX22FFT_CTRL1_4_block2.vhd
vcom  TWDLROM_5_1_block2.vhd
vcom  Complex4Multiply_block9.vhd
vcom  SDFCommutator5_block2.vhd
vcom  RADIX22FFT_SDF1_5_block2.vhd
vcom  RADIX22FFT_CTRL1_5_block2.vhd
vcom  SDFCommutator6_block2.vhd
vcom  RADIX22FFT_SDF2_6_block2.vhd
vcom  RADIX22FFT_CTRL1_6_block2.vhd
vcom  TWDLROM_7_1_block2.vhd
vcom  Complex4Multiply_block10.vhd
vcom  SDFCommutator7_block2.vhd
vcom  RADIX22FFT_SDF1_7_block2.vhd
vcom  RADIX22FFT_CTRL1_1_block6.vhd
vcom  RADIX2FFT_bitNatural_block2.vhd
vcom  RowFFT.vhd
vcom  Curr2_DFFT.vhd
vcom  BankBit_block1.vhd
vcom  LowerRAM_block1.vhd
vcom  SwapAddr_block1.vhd
vcom  UpperRAM_block1.vhd
vcom  CounterDelay_block1.vhd
vcom  CornerTurnMemory_block1.vhd
vcom  Pixel_Control_Bus_Creator_block1.vhd
vcom  pixelBusGenerator_block1.vhd
vcom  SDFCommutator1_block3.vhd
vcom  RADIX22FFT_SDF1_1_block3.vhd
vcom  RADIX22FFT_CTRL1_1_block7.vhd
vcom  SDFCommutator2_block3.vhd
vcom  RADIX22FFT_SDF2_2_block3.vhd
vcom  RADIX22FFT_CTRL1_2_block3.vhd
vcom  TWDLROM_3_1_block3.vhd
vcom  Complex4Multiply_block11.vhd
vcom  SDFCommutator3_block3.vhd
vcom  RADIX22FFT_SDF1_3_block3.vhd
vcom  RADIX22FFT_CTRL1_3_block3.vhd
vcom  SDFCommutator4_block3.vhd
vcom  RADIX22FFT_SDF2_4_block3.vhd
vcom  RADIX22FFT_CTRL1_4_block3.vhd
vcom  TWDLROM_5_1_block3.vhd
vcom  Complex4Multiply_block12.vhd
vcom  SDFCommutator5_block3.vhd
vcom  RADIX22FFT_SDF1_5_block3.vhd
vcom  RADIX22FFT_CTRL1_5_block3.vhd
vcom  SDFCommutator6_block3.vhd
vcom  RADIX22FFT_SDF2_6_block3.vhd
vcom  RADIX22FFT_CTRL1_6_block3.vhd
vcom  TWDLROM_7_1_block3.vhd
vcom  Complex4Multiply_block13.vhd
vcom  SDFCommutator7_block3.vhd
vcom  RADIX22FFT_SDF1_7_block3.vhd
vcom  RADIX22FFT_CTRL1_1_block8.vhd
vcom  RADIX2FFT_bitNatural_block3.vhd
vcom  ColumnFFT_block.vhd
vcom  SDFCommutator1_block4.vhd
vcom  RADIX22FFT_SDF1_1_block4.vhd
vcom  RADIX22FFT_CTRL1_1_block9.vhd
vcom  SDFCommutator2_block4.vhd
vcom  RADIX22FFT_SDF2_2_block4.vhd
vcom  RADIX22FFT_CTRL1_2_block4.vhd
vcom  TWDLROM_3_1_block4.vhd
vcom  Complex4Multiply_block14.vhd
vcom  SDFCommutator3_block4.vhd
vcom  RADIX22FFT_SDF1_3_block4.vhd
vcom  RADIX22FFT_CTRL1_3_block4.vhd
vcom  SDFCommutator4_block4.vhd
vcom  RADIX22FFT_SDF2_4_block4.vhd
vcom  RADIX22FFT_CTRL1_4_block4.vhd
vcom  TWDLROM_5_1_block4.vhd
vcom  Complex4Multiply_block15.vhd
vcom  SDFCommutator5_block4.vhd
vcom  RADIX22FFT_SDF1_5_block4.vhd
vcom  RADIX22FFT_CTRL1_5_block4.vhd
vcom  SDFCommutator6_block4.vhd
vcom  RADIX22FFT_SDF2_6_block4.vhd
vcom  RADIX22FFT_CTRL1_6_block4.vhd
vcom  TWDLROM_7_1_block4.vhd
vcom  Complex4Multiply_block16.vhd
vcom  SDFCommutator7_block4.vhd
vcom  RADIX22FFT_SDF1_7_block4.vhd
vcom  RADIX22FFT_CTRL1_1_block10.vhd
vcom  RADIX2FFT_bitNatural_block4.vhd
vcom  RowFFT_block.vhd
vcom  Prev2_DFFT.vhd
vcom  SimpleDualPortRAM_generic_block1.vhd
vcom  Pixel_Stream_Aligner.vhd
vcom  Pixel_Stream_Aligner1.vhd
vcom  StreamAlignment.vhd
vcom  alpha2_DCorrelation.vhd
vcom  MaxCtrl.vhd
vcom  HV_Counter.vhd
vcom  Divide2.vhd
vcom  Divide3_block.vhd
vcom  MaxCorrelation.vhd
vcom  ROIUpdate.vhd
vcom  ROIUpdate_block.vhd
vcom  Track.vhd
vcom  Lookup_Table.vhd
vcom  Gamma_Corrector.vhd
vcom  dataReadFSM.vhd
vcom  dataWriteFSM.vhd
vcom  counterBank.vhd
vcom  accumulatorBank.vhd
vcom  accumulatorBankVar.vhd
vcom  Lookup_Table_block.vhd
vcom  Normalization.vhd
vcom  Lookup_Table_block1.vhd
vcom  Normalization_Var.vhd
vcom  calcMean.vhd
vcom  SQRTBitSet.vhd
vcom  Image_Statistics.vhd
vcom  Product.vhd
vcom  Divide1.vhd
vcom  CurrPreprocess.vhd
vcom  Lookup_Table_block2.vhd
vcom  Gamma_Corrector_block.vhd
vcom  dataReadFSM_block.vhd
vcom  dataWriteFSM_block.vhd
vcom  counterBank_block.vhd
vcom  accumulatorBank_block.vhd
vcom  accumulatorBankVar_block.vhd
vcom  Lookup_Table_block3.vhd
vcom  Normalization_block.vhd
vcom  Lookup_Table_block4.vhd
vcom  Normalization_Var_block.vhd
vcom  calcMean_block.vhd
vcom  SQRTBitSet_block.vhd
vcom  Image_Statistics_block.vhd
vcom  Product_block.vhd
vcom  Divide2_block.vhd
vcom  PrevPreprocess.vhd
vcom  InputControlValidation.vhd
vcom  DataReadController.vhd
vcom  LineSpaceAverager.vhd
vcom  LineInfoStore.vhd
vcom  PushPopCounterOne.vhd
vcom  PushPopCounter.vhd
vcom  DATA_MEMORY.vhd
vcom  LineInfoStore_block.vhd
vcom  PaddingController.vhd
vcom  GateProcessData.vhd
vcom  Horizontal_Padder.vhd
vcom  Vertical_Padding_Counter.vhd
vcom  Vertical_Padder.vhd
vcom  LineBuffer.vhd
vcom  SobelCore.vhd
vcom  GenerateBinaryImage.vhd
vcom  Edge_Detector.vhd
vcom  ROI_Selector.vhd
vcom  ROI_Selector1.vhd
vcom  Preprocess.vhd
vcom  ObjectTrackerHDL.vhd
