-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ObjectTrackerHDL\Track.vhd
-- Created: 2024-12-03 00:37:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Track
-- Source Path: ObjectTrackerHDL/ObjectTrackerHDL/Track
-- Hierarchy Level: 1
-- Model version: 3.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ObjectTrackerHDL_pkg.ALL;

ENTITY Track IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        prevPixelIn                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        prevCtrlIn_valid                  :   IN    std_logic;
        currPixelIn                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        currCtrlIn_valid                  :   IN    std_logic;
        frameCtrl_vEnd                    :   IN    std_logic;
        prevROIOut                        :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- uint16 [4]
        currROIOut                        :   OUT   vector_of_std_logic_vector16(0 TO 3)  -- uint16 [4]
        );
END Track;


ARCHITECTURE rtl OF Track IS

  -- Component Declarations
  COMPONENT alpha2_DCorrelation
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          prevPixelIn                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          prevCtrlIn_valid                :   IN    std_logic;
          currPixelIn                     :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          currCtrlIn_valid                :   IN    std_logic;
          streamCtrlIn                    :   IN    std_logic;
          frameCtrl_vEnd                  :   IN    std_logic;
          pixelOut                        :   OUT   std_logic_vector(23 DOWNTO 0);  -- sfix24_En16
          ctrlOut_hStart                  :   OUT   std_logic;
          ctrlOut_hEnd                    :   OUT   std_logic;
          ctrlOut_vStart                  :   OUT   std_logic;
          ctrlOut_vEnd                    :   OUT   std_logic;
          ctrlOut_valid                   :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT MaxCorrelation
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          pixelIn                         :   IN    std_logic_vector(23 DOWNTO 0);  -- sfix24_En16
          ctrlIn_hStart                   :   IN    std_logic;
          ctrlIn_hEnd                     :   IN    std_logic;
          ctrlIn_vStart                   :   IN    std_logic;
          ctrlIn_vEnd                     :   IN    std_logic;
          ctrlIn_valid                    :   IN    std_logic;
          frameCtrl_vEnd                  :   IN    std_logic;
          maxCol                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
          maxRow                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- uint16
          );
  END COMPONENT;

  COMPONENT ROIUpdate_block
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          maxCol                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          maxRow                          :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          frameCtrl_vEnd                  :   IN    std_logic;
          streamCtrlOut                   :   OUT   std_logic;
          prevROI                         :   OUT   vector_of_std_logic_vector16(0 TO 3);  -- uint16 [4]
          currROI                         :   OUT   vector_of_std_logic_vector16(0 TO 3)  -- uint16 [4]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : alpha2_DCorrelation
    USE ENTITY work.alpha2_DCorrelation(rtl);

  FOR ALL : MaxCorrelation
    USE ENTITY work.MaxCorrelation(rtl);

  FOR ALL : ROIUpdate_block
    USE ENTITY work.ROIUpdate_block(rtl);

  -- Signals
  SIGNAL alpha_reg_3                      : std_logic_vector(19 DOWNTO 0);  -- ufix1 [20]
  SIGNAL Delay7_out1_vEnd                 : std_logic;
  SIGNAL ROIUpdate_out1                   : std_logic;
  SIGNAL alpha2_DCorrelation_out1         : std_logic_vector(23 DOWNTO 0);  -- ufix24
  SIGNAL alpha2_DCorrelation_out2_hStart  : std_logic;
  SIGNAL alpha2_DCorrelation_out2_hEnd    : std_logic;
  SIGNAL alpha2_DCorrelation_out2_vStart  : std_logic;
  SIGNAL alpha2_DCorrelation_out2_vEnd    : std_logic;
  SIGNAL alpha2_DCorrelation_out2_valid   : std_logic;
  SIGNAL MaxCorrelation_out1              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL MaxCorrelation_out2              : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL ROIUpdate_out2                   : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]
  SIGNAL ROIUpdate_out3                   : vector_of_std_logic_vector16(0 TO 3);  -- ufix16 [4]

BEGIN
  -- Tracking HDL Subsystem performs 2D correlation, calculates maximum of 2D correlation point and updates the ROI

  u_2_DCorrelation : alpha2_DCorrelation
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              prevPixelIn => prevPixelIn,  -- sfix32_En28
              prevCtrlIn_valid => prevCtrlIn_valid,
              currPixelIn => currPixelIn,  -- sfix32_En28
              currCtrlIn_valid => currCtrlIn_valid,
              streamCtrlIn => ROIUpdate_out1,
              frameCtrl_vEnd => frameCtrl_vEnd,
              pixelOut => alpha2_DCorrelation_out1,  -- sfix24_En16
              ctrlOut_hStart => alpha2_DCorrelation_out2_hStart,
              ctrlOut_hEnd => alpha2_DCorrelation_out2_hEnd,
              ctrlOut_vStart => alpha2_DCorrelation_out2_vStart,
              ctrlOut_vEnd => alpha2_DCorrelation_out2_vEnd,
              ctrlOut_valid => alpha2_DCorrelation_out2_valid
              );

  u_MaxCorrelation : MaxCorrelation
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              pixelIn => alpha2_DCorrelation_out1,  -- sfix24_En16
              ctrlIn_hStart => alpha2_DCorrelation_out2_hStart,
              ctrlIn_hEnd => alpha2_DCorrelation_out2_hEnd,
              ctrlIn_vStart => alpha2_DCorrelation_out2_vStart,
              ctrlIn_vEnd => alpha2_DCorrelation_out2_vEnd,
              ctrlIn_valid => alpha2_DCorrelation_out2_valid,
              frameCtrl_vEnd => frameCtrl_vEnd,
              maxCol => MaxCorrelation_out1,  -- uint16
              maxRow => MaxCorrelation_out2  -- uint16
              );

  u_ROIUpdate : ROIUpdate_block
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              maxCol => MaxCorrelation_out1,  -- uint16
              maxRow => MaxCorrelation_out2,  -- uint16
              frameCtrl_vEnd => Delay7_out1_vEnd,
              streamCtrlOut => ROIUpdate_out1,
              prevROI => ROIUpdate_out2,  -- uint16 [4]
              currROI => ROIUpdate_out3  -- uint16 [4]
              );

  c_3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      alpha_reg_3 <= (OTHERS => '0');
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        alpha_reg_3(0) <= frameCtrl_vEnd;
        alpha_reg_3(19 DOWNTO 1) <= alpha_reg_3(18 DOWNTO 0);
      END IF;
    END IF;
  END PROCESS c_3_process;

  Delay7_out1_vEnd <= alpha_reg_3(19);

  prevROIOut <= ROIUpdate_out2;

  currROIOut <= ROIUpdate_out3;

END rtl;

