-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\ObjectTrackerHDL\TWDLROM_3_1_block4.vhd
-- Created: 2024-12-03 00:37:46
-- 
-- Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: TWDLROM_3_1_block4
-- Source Path: ObjectTrackerHDL/ObjectTrackerHDL/Track/2-DCorrelation/Prev2-DFFT/RowFFT/TWDLROM_3_1
-- Hierarchy Level: 5
-- Model version: 3.7
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.ObjectTrackerHDL_pkg.ALL;

ENTITY TWDLROM_3_1_block4 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        dout_2_1_vld                      :   IN    std_logic;
        twdl_3_1_re                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En30
        twdl_3_1_im                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En30
        );
END TWDLROM_3_1_block4;


ARCHITECTURE rtl OF TWDLROM_3_1_block4 IS

  -- Constants
  CONSTANT Twiddle_re_table_data          : vector_of_signed32(0 TO 15) := 
    (to_signed(1073741824, 32), to_signed(1072448455, 32), to_signed(1068571464, 32), to_signed(1062120190, 32),
     to_signed(1053110176, 32), to_signed(1041563127, 32), to_signed(1027506862, 32), to_signed(1010975242, 32),
     to_signed(992008094, 32), to_signed(970651112, 32), to_signed(946955747, 32), to_signed(920979082, 32),
     to_signed(892783698, 32), to_signed(862437520, 32), to_signed(830013654, 32), to_signed(795590213, 32));  -- sfix32 [16]
  CONSTANT Twiddle_im_table_data          : vector_of_signed32(0 TO 15) := 
    (to_signed(0, 32), to_signed(-52686014, 32), to_signed(-105245103, 32), to_signed(-157550647, 32),
     to_signed(-209476638, 32), to_signed(-260897982, 32), to_signed(-311690799, 32), to_signed(-361732726, 32),
     to_signed(-410903207, 32), to_signed(-459083786, 32), to_signed(-506158392, 32), to_signed(-552013618, 32),
     to_signed(-596538995, 32), to_signed(-639627258, 32), to_signed(-681174602, 32), to_signed(-721080937, 32));  -- sfix32 [16]

  -- Signals
  SIGNAL Radix22TwdlMapping_cnt           : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Radix22TwdlMapping_phase         : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Radix22TwdlMapping_octantReg1    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Radix22TwdlMapping_twdlAddr_raw  : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Radix22TwdlMapping_twdlAddrMap   : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Radix22TwdlMapping_twdl45Reg     : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg1      : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg2      : std_logic;
  SIGNAL Radix22TwdlMapping_cnt_next      : unsigned(4 DOWNTO 0);  -- ufix5
  SIGNAL Radix22TwdlMapping_phase_next    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL Radix22TwdlMapping_octantReg1_next : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Radix22TwdlMapping_twdlAddr_raw_next : unsigned(6 DOWNTO 0);  -- ufix7
  SIGNAL Radix22TwdlMapping_twdlAddrMap_next : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL Radix22TwdlMapping_twdl45Reg_next : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg1_next : std_logic;
  SIGNAL Radix22TwdlMapping_dvldReg2_next : std_logic;
  SIGNAL twdlAddr                         : unsigned(3 DOWNTO 0);  -- ufix4
  SIGNAL twdlAddrVld                      : std_logic;
  SIGNAL twdlOctant                       : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL twdl45                           : std_logic;
  SIGNAL twiddleS_re                      : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twiddleReg_re                    : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twiddleS_im                      : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twiddleReg_im                    : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twdlOctantReg                    : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL twdl45Reg                        : std_logic;
  SIGNAL twdl_3_1_re_tmp                  : signed(31 DOWNTO 0);  -- sfix32_En30
  SIGNAL twdl_3_1_im_tmp                  : signed(31 DOWNTO 0);  -- sfix32_En30

BEGIN
  -- Radix22TwdlMapping
  Radix22TwdlMapping_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Radix22TwdlMapping_octantReg1 <= to_unsigned(16#0#, 3);
      Radix22TwdlMapping_twdlAddr_raw <= to_unsigned(16#00#, 7);
      Radix22TwdlMapping_twdlAddrMap <= to_unsigned(16#0#, 4);
      Radix22TwdlMapping_twdl45Reg <= '0';
      Radix22TwdlMapping_dvldReg1 <= '0';
      Radix22TwdlMapping_dvldReg2 <= '0';
      Radix22TwdlMapping_cnt <= to_unsigned(16#00#, 5);
      Radix22TwdlMapping_phase <= to_unsigned(16#0#, 2);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Radix22TwdlMapping_cnt <= Radix22TwdlMapping_cnt_next;
        Radix22TwdlMapping_phase <= Radix22TwdlMapping_phase_next;
        Radix22TwdlMapping_octantReg1 <= Radix22TwdlMapping_octantReg1_next;
        Radix22TwdlMapping_twdlAddr_raw <= Radix22TwdlMapping_twdlAddr_raw_next;
        Radix22TwdlMapping_twdlAddrMap <= Radix22TwdlMapping_twdlAddrMap_next;
        Radix22TwdlMapping_twdl45Reg <= Radix22TwdlMapping_twdl45Reg_next;
        Radix22TwdlMapping_dvldReg1 <= Radix22TwdlMapping_dvldReg1_next;
        Radix22TwdlMapping_dvldReg2 <= Radix22TwdlMapping_dvldReg2_next;
      END IF;
    END IF;
  END PROCESS Radix22TwdlMapping_process;

  Radix22TwdlMapping_output : PROCESS (Radix22TwdlMapping_cnt, Radix22TwdlMapping_dvldReg1,
       Radix22TwdlMapping_dvldReg2, Radix22TwdlMapping_octantReg1,
       Radix22TwdlMapping_phase, Radix22TwdlMapping_twdl45Reg,
       Radix22TwdlMapping_twdlAddrMap, Radix22TwdlMapping_twdlAddr_raw,
       dout_2_1_vld)
    VARIABLE octant : unsigned(2 DOWNTO 0);
    VARIABLE cnt_cast : unsigned(6 DOWNTO 0);
    VARIABLE sub_cast : signed(15 DOWNTO 0);
    VARIABLE sub_temp : signed(15 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(8 DOWNTO 0);
    VARIABLE sub_temp_0 : signed(8 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(8 DOWNTO 0);
    VARIABLE sub_temp_1 : signed(8 DOWNTO 0);
    VARIABLE sub_cast_2 : signed(15 DOWNTO 0);
    VARIABLE sub_temp_2 : signed(15 DOWNTO 0);
    VARIABLE sub_cast_3 : signed(15 DOWNTO 0);
    VARIABLE sub_temp_3 : signed(15 DOWNTO 0);
  BEGIN
    sub_temp := to_signed(16#0000#, 16);
    sub_temp_0 := to_signed(16#000#, 9);
    sub_temp_1 := to_signed(16#000#, 9);
    sub_temp_2 := to_signed(16#0000#, 16);
    sub_temp_3 := to_signed(16#0000#, 16);
    sub_cast_3 := to_signed(16#0000#, 16);
    cnt_cast := to_unsigned(16#00#, 7);
    sub_cast_2 := to_signed(16#0000#, 16);
    sub_cast_1 := to_signed(16#000#, 9);
    sub_cast_0 := to_signed(16#000#, 9);
    sub_cast := to_signed(16#0000#, 16);
    Radix22TwdlMapping_cnt_next <= Radix22TwdlMapping_cnt;
    Radix22TwdlMapping_phase_next <= Radix22TwdlMapping_phase;
    Radix22TwdlMapping_dvldReg2_next <= Radix22TwdlMapping_dvldReg1;
    Radix22TwdlMapping_dvldReg1_next <= dout_2_1_vld;
    CASE Radix22TwdlMapping_twdlAddr_raw IS
      WHEN "0010000" =>
        octant := to_unsigned(16#0#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN "0100000" =>
        octant := to_unsigned(16#1#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
      WHEN "0110000" =>
        octant := to_unsigned(16#2#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN "1000000" =>
        octant := to_unsigned(16#3#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
      WHEN "1010000" =>
        octant := to_unsigned(16#4#, 3);
        Radix22TwdlMapping_twdl45Reg_next <= '1';
      WHEN OTHERS => 
        octant := Radix22TwdlMapping_twdlAddr_raw(6 DOWNTO 4);
        Radix22TwdlMapping_twdl45Reg_next <= '0';
    END CASE;
    Radix22TwdlMapping_octantReg1_next <= octant;
    CASE octant IS
      WHEN "000" =>
        Radix22TwdlMapping_twdlAddrMap_next <= Radix22TwdlMapping_twdlAddr_raw(3 DOWNTO 0);
      WHEN "001" =>
        sub_cast_0 := signed(resize(Radix22TwdlMapping_twdlAddr_raw, 9));
        sub_temp_0 := to_signed(16#020#, 9) - sub_cast_0;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_0(3 DOWNTO 0));
      WHEN "010" =>
        sub_cast_1 := signed(resize(Radix22TwdlMapping_twdlAddr_raw, 9));
        sub_temp_1 := sub_cast_1 - to_signed(16#020#, 9);
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_1(3 DOWNTO 0));
      WHEN "011" =>
        sub_cast_2 := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0', 16));
        sub_temp_2 := to_signed(16#0400#, 16) - sub_cast_2;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_2(7 DOWNTO 4));
      WHEN "100" =>
        sub_cast_3 := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0', 16));
        sub_temp_3 := sub_cast_3 - to_signed(16#0400#, 16);
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp_3(7 DOWNTO 4));
      WHEN OTHERS => 
        sub_cast := signed(resize(Radix22TwdlMapping_twdlAddr_raw & '0' & '0' & '0' & '0', 16));
        sub_temp := to_signed(16#0600#, 16) - sub_cast;
        Radix22TwdlMapping_twdlAddrMap_next <= unsigned(sub_temp(7 DOWNTO 4));
    END CASE;
    IF Radix22TwdlMapping_phase = to_unsigned(16#0#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= to_unsigned(16#00#, 7);
    ELSIF Radix22TwdlMapping_phase = to_unsigned(16#1#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= resize(Radix22TwdlMapping_cnt, 7) sll 1;
    ELSIF Radix22TwdlMapping_phase = to_unsigned(16#2#, 2) THEN 
      Radix22TwdlMapping_twdlAddr_raw_next <= resize(Radix22TwdlMapping_cnt, 7);
    ELSE 
      cnt_cast := resize(Radix22TwdlMapping_cnt, 7);
      Radix22TwdlMapping_twdlAddr_raw_next <= (cnt_cast sll 1) + cnt_cast;
    END IF;
    IF dout_2_1_vld = '1' AND (Radix22TwdlMapping_cnt > to_unsigned(16#1E#, 5)) THEN 
      Radix22TwdlMapping_phase_next <= Radix22TwdlMapping_phase + to_unsigned(16#1#, 2);
    END IF;
    IF dout_2_1_vld = '1' THEN 
      Radix22TwdlMapping_cnt_next <= Radix22TwdlMapping_cnt + to_unsigned(16#01#, 5);
    END IF;
    twdlAddr <= Radix22TwdlMapping_twdlAddrMap;
    twdlAddrVld <= Radix22TwdlMapping_dvldReg2;
    twdlOctant <= Radix22TwdlMapping_octantReg1;
    twdl45 <= Radix22TwdlMapping_twdl45Reg;
  END PROCESS Radix22TwdlMapping_output;


  -- Twiddle ROM1
  twiddleS_re <= Twiddle_re_table_data(to_integer(twdlAddr));

  TWIDDLEROM_RE_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddleReg_re <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twiddleReg_re <= twiddleS_re;
      END IF;
    END IF;
  END PROCESS TWIDDLEROM_RE_process;


  -- Twiddle ROM2
  twiddleS_im <= Twiddle_im_table_data(to_integer(twdlAddr));

  TWIDDLEROM_IM_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twiddleReg_im <= to_signed(0, 32);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twiddleReg_im <= twiddleS_im;
      END IF;
    END IF;
  END PROCESS TWIDDLEROM_IM_process;


  intdelay_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twdlOctantReg <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twdlOctantReg <= twdlOctant;
      END IF;
    END IF;
  END PROCESS intdelay_process;


  intdelay_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      twdl45Reg <= '0';
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        twdl45Reg <= twdl45;
      END IF;
    END IF;
  END PROCESS intdelay_1_process;


  -- Radix22TwdlOctCorr
  Radix22TwdlOctCorr_output : PROCESS (twdl45Reg, twdlOctantReg, twiddleReg_im, twiddleReg_re)
    VARIABLE twdlIn_re : signed(31 DOWNTO 0);
    VARIABLE twdlIn_im : signed(31 DOWNTO 0);
    VARIABLE cast : signed(32 DOWNTO 0);
    VARIABLE cast_0 : signed(32 DOWNTO 0);
    VARIABLE cast_1 : signed(32 DOWNTO 0);
    VARIABLE cast_2 : signed(32 DOWNTO 0);
    VARIABLE cast_3 : signed(32 DOWNTO 0);
    VARIABLE cast_4 : signed(32 DOWNTO 0);
    VARIABLE cast_5 : signed(32 DOWNTO 0);
    VARIABLE cast_6 : signed(32 DOWNTO 0);
    VARIABLE cast_7 : signed(32 DOWNTO 0);
    VARIABLE cast_8 : signed(32 DOWNTO 0);
    VARIABLE cast_9 : signed(32 DOWNTO 0);
    VARIABLE cast_10 : signed(32 DOWNTO 0);
  BEGIN
    cast_0 := to_signed(0, 33);
    cast_2 := to_signed(0, 33);
    cast_4 := to_signed(0, 33);
    cast_6 := to_signed(0, 33);
    cast_8 := to_signed(0, 33);
    cast_10 := to_signed(0, 33);
    cast_3 := to_signed(0, 33);
    cast_9 := to_signed(0, 33);
    cast_1 := to_signed(0, 33);
    cast_7 := to_signed(0, 33);
    cast := to_signed(0, 33);
    cast_5 := to_signed(0, 33);
    twdlIn_re := twiddleReg_re;
    twdlIn_im := twiddleReg_im;
    IF twdl45Reg = '1' THEN 
      CASE twdlOctantReg IS
        WHEN "000" =>
          twdlIn_re := to_signed(759250125, 32);
          twdlIn_im := to_signed(-759250125, 32);
        WHEN "010" =>
          twdlIn_re := to_signed(-759250125, 32);
          twdlIn_im := to_signed(-759250125, 32);
        WHEN "100" =>
          twdlIn_re := to_signed(-759250125, 32);
          twdlIn_im := to_signed(759250125, 32);
        WHEN OTHERS => 
          twdlIn_re := to_signed(759250125, 32);
          twdlIn_im := to_signed(-759250125, 32);
      END CASE;
    ELSE 
      CASE twdlOctantReg IS
        WHEN "000" =>
          NULL;
        WHEN "001" =>
          cast := resize(twiddleReg_im, 33);
          cast_0 :=  - (cast);
          twdlIn_re := cast_0(31 DOWNTO 0);
          cast_5 := resize(twiddleReg_re, 33);
          cast_6 :=  - (cast_5);
          twdlIn_im := cast_6(31 DOWNTO 0);
        WHEN "010" =>
          twdlIn_re := twiddleReg_im;
          cast_7 := resize(twiddleReg_re, 33);
          cast_8 :=  - (cast_7);
          twdlIn_im := cast_8(31 DOWNTO 0);
        WHEN "011" =>
          cast_1 := resize(twiddleReg_re, 33);
          cast_2 :=  - (cast_1);
          twdlIn_re := cast_2(31 DOWNTO 0);
          twdlIn_im := twiddleReg_im;
        WHEN "100" =>
          cast_3 := resize(twiddleReg_re, 33);
          cast_4 :=  - (cast_3);
          twdlIn_re := cast_4(31 DOWNTO 0);
          cast_9 := resize(twiddleReg_im, 33);
          cast_10 :=  - (cast_9);
          twdlIn_im := cast_10(31 DOWNTO 0);
        WHEN OTHERS => 
          twdlIn_re := twiddleReg_im;
          twdlIn_im := twiddleReg_re;
      END CASE;
    END IF;
    twdl_3_1_re_tmp <= twdlIn_re;
    twdl_3_1_im_tmp <= twdlIn_im;
  END PROCESS Radix22TwdlOctCorr_output;


  twdl_3_1_re <= std_logic_vector(twdl_3_1_re_tmp);

  twdl_3_1_im <= std_logic_vector(twdl_3_1_im_tmp);

END rtl;

